version: '3'
services:
  website:
    image: aadah
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
    environment:
      - HTTP_PORT=${HTTP_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB=${DB}
    command: npm start
    volumes:
      - type: bind
        source: ./
        target: /aadah
    depends_on:
      mongodb:
        condition: service_healthy
  mongodb:
    image: mongo:3.4-xenial
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
    healthcheck:
      test: mongo -u ${DB_USER} -p ${DB_PASS} mongodb://mongodb/${DB} --eval "print('live')"
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - type: bind
        source: ${DB_DIR}
        target: /data/db
